//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morada_da_paz_Forms.Morada_da_paz_WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_WebService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nome_completoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome_completo {
            get {
                return this.Nome_completoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nome_completoField, value) != true)) {
                    this.Nome_completoField = value;
                    this.RaisePropertyChanged("Nome_completo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="unidade_residencial", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class unidade_residencial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Numero_residenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero_residencia {
            get {
                return this.Numero_residenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Numero_residenciaField, value) != true)) {
                    this.Numero_residenciaField = value;
                    this.RaisePropertyChanged("Numero_residencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="advertencia", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class advertencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="especializacao_usuario", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class especializacao_usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="multa", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class multa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ocorrencia", Namespace="http://schemas.datacontract.org/2004/07/Morada_da_paz_Biblioteca.basicas")]
    [System.SerializableAttribute()]
    public partial class ocorrencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Numero_ocorrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero_ocorrencia {
            get {
                return this.Numero_ocorrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Numero_ocorrenciaField, value) != true)) {
                    this.Numero_ocorrenciaField = value;
                    this.RaisePropertyChanged("Numero_ocorrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Morada_da_paz_WebService.IServiceMoradaDaPaz")]
    public interface IServiceMoradaDaPaz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/GetData", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/GetData", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/GetDataUsingDataContractResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType GetDataUsingDataContract(Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType> GetDataUsingDataContractAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inseirUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inseirUsuarioResponse")]
        void inseirUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inseirUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inseirUsuarioResponse")]
        System.Threading.Tasks.Task inseirUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarUsuarioResponse")]
        void editarUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarUsuarioResponse")]
        System.Threading.Tasks.Task editarUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarUsuarios", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarUsuariosResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.usuario[] listarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarUsuarios", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarUsuariosResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.usuario[]> listarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUsuarioResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.usuario pesquisaUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUsuario", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUsuarioResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.usuario> pesquisaUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inseirUnidadeResidencial", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inseirUnidadeResidencialResponse")]
        void inseirUnidadeResidencial(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inseirUnidadeResidencial", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inseirUnidadeResidencialResponse")]
        System.Threading.Tasks.Task inseirUnidadeResidencialAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editaUnidadeResisencial", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editaUnidadeResisencialResponse")]
        void editaUnidadeResisencial(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editaUnidadeResisencial", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editaUnidadeResisencialResponse")]
        System.Threading.Tasks.Task editaUnidadeResisencialAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarUnidades", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarUnidadesResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial[] listarUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarUnidades", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarUnidadesResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial[]> listarUnidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUnidade", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUnidadeResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial pesquisaUnidade(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUnidade", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaUnidadeResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial> pesquisaUnidadeAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirAdvertenciaResponse")]
        void inserirAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirAdvertenciaResponse")]
        System.Threading.Tasks.Task inserirAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarAdvertenciaResponse")]
        void editarAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarAdvertenciaResponse")]
        System.Threading.Tasks.Task editarAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarAdvertencias", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarAdvertenciasResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia[] listarAdvertencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarAdvertencias", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarAdvertenciasResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia[]> listarAdvertenciasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaAdvertenciaResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia pesquisaAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaAdvertencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaAdvertenciaResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia> pesquisaAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirEspecializacaoResponse")]
        void inserirEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirEspecializacaoResponse")]
        System.Threading.Tasks.Task inserirEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarEspecializacaoResponse")]
        void editarEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarEspecializacaoResponse")]
        System.Threading.Tasks.Task editarEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarEspecializacaoResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario[] listarEspecializacao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarEspecializacaoResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario[]> listarEspecializacaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaEspecializacaoResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario pesquisaEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaEspecializacao", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaEspecializacaoResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario> pesquisaEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirMultaResponse")]
        void inserirMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirMultaResponse")]
        System.Threading.Tasks.Task inserirMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarMultaResponse")]
        void editarMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarMultaResponse")]
        System.Threading.Tasks.Task editarMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarMultaResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.multa[] listarMulta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarMultaResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.multa[]> listarMultaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaMultaResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.multa pesquisaMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaMulta", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaMultaResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.multa> pesquisaMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirOcorrenciaResponse")]
        void inserirOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/inserirOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/inserirOcorrenciaResponse")]
        System.Threading.Tasks.Task inserirOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarOcorrenciaResponse")]
        void editarOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/editarOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/editarOcorrenciaResponse")]
        System.Threading.Tasks.Task editarOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarOcorrencias", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarOcorrenciasResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia[] listarOcorrencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/listarOcorrencias", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/listarOcorrenciasResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia[]> listarOcorrenciasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaOcorrenciaResponse")]
        Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia pesquisaOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMoradaDaPaz/pesquisaOcorrencia", ReplyAction="http://tempuri.org/IServiceMoradaDaPaz/pesquisaOcorrenciaResponse")]
        System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia> pesquisaOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMoradaDaPazChannel : Morada_da_paz_Forms.Morada_da_paz_WebService.IServiceMoradaDaPaz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMoradaDaPazClient : System.ServiceModel.ClientBase<Morada_da_paz_Forms.Morada_da_paz_WebService.IServiceMoradaDaPaz>, Morada_da_paz_Forms.Morada_da_paz_WebService.IServiceMoradaDaPaz {
        
        public ServiceMoradaDaPazClient() {
        }
        
        public ServiceMoradaDaPazClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMoradaDaPazClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMoradaDaPazClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMoradaDaPazClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType GetDataUsingDataContract(Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType> GetDataUsingDataContractAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void inseirUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            base.Channel.inseirUsuario(u);
        }
        
        public System.Threading.Tasks.Task inseirUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            return base.Channel.inseirUsuarioAsync(u);
        }
        
        public void editarUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            base.Channel.editarUsuario(u);
        }
        
        public System.Threading.Tasks.Task editarUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            return base.Channel.editarUsuarioAsync(u);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.usuario[] listarUsuarios() {
            return base.Channel.listarUsuarios();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.usuario[]> listarUsuariosAsync() {
            return base.Channel.listarUsuariosAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.usuario pesquisaUsuario(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            return base.Channel.pesquisaUsuario(u);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.usuario> pesquisaUsuarioAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.usuario u) {
            return base.Channel.pesquisaUsuarioAsync(u);
        }
        
        public void inseirUnidadeResidencial(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            base.Channel.inseirUnidadeResidencial(ur);
        }
        
        public System.Threading.Tasks.Task inseirUnidadeResidencialAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            return base.Channel.inseirUnidadeResidencialAsync(ur);
        }
        
        public void editaUnidadeResisencial(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            base.Channel.editaUnidadeResisencial(ur);
        }
        
        public System.Threading.Tasks.Task editaUnidadeResisencialAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            return base.Channel.editaUnidadeResisencialAsync(ur);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial[] listarUnidades() {
            return base.Channel.listarUnidades();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial[]> listarUnidadesAsync() {
            return base.Channel.listarUnidadesAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial pesquisaUnidade(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            return base.Channel.pesquisaUnidade(ur);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial> pesquisaUnidadeAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.unidade_residencial ur) {
            return base.Channel.pesquisaUnidadeAsync(ur);
        }
        
        public void inserirAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            base.Channel.inserirAdvertencia(a);
        }
        
        public System.Threading.Tasks.Task inserirAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            return base.Channel.inserirAdvertenciaAsync(a);
        }
        
        public void editarAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            base.Channel.editarAdvertencia(a);
        }
        
        public System.Threading.Tasks.Task editarAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            return base.Channel.editarAdvertenciaAsync(a);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia[] listarAdvertencias() {
            return base.Channel.listarAdvertencias();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia[]> listarAdvertenciasAsync() {
            return base.Channel.listarAdvertenciasAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia pesquisaAdvertencia(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            return base.Channel.pesquisaAdvertencia(a);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia> pesquisaAdvertenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.advertencia a) {
            return base.Channel.pesquisaAdvertenciaAsync(a);
        }
        
        public void inserirEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            base.Channel.inserirEspecializacao(eu);
        }
        
        public System.Threading.Tasks.Task inserirEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            return base.Channel.inserirEspecializacaoAsync(eu);
        }
        
        public void editarEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            base.Channel.editarEspecializacao(eu);
        }
        
        public System.Threading.Tasks.Task editarEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            return base.Channel.editarEspecializacaoAsync(eu);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario[] listarEspecializacao() {
            return base.Channel.listarEspecializacao();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario[]> listarEspecializacaoAsync() {
            return base.Channel.listarEspecializacaoAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario pesquisaEspecializacao(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            return base.Channel.pesquisaEspecializacao(eu);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario> pesquisaEspecializacaoAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.especializacao_usuario eu) {
            return base.Channel.pesquisaEspecializacaoAsync(eu);
        }
        
        public void inserirMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            base.Channel.inserirMulta(m);
        }
        
        public System.Threading.Tasks.Task inserirMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            return base.Channel.inserirMultaAsync(m);
        }
        
        public void editarMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            base.Channel.editarMulta(m);
        }
        
        public System.Threading.Tasks.Task editarMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            return base.Channel.editarMultaAsync(m);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.multa[] listarMulta() {
            return base.Channel.listarMulta();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.multa[]> listarMultaAsync() {
            return base.Channel.listarMultaAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.multa pesquisaMulta(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            return base.Channel.pesquisaMulta(m);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.multa> pesquisaMultaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.multa m) {
            return base.Channel.pesquisaMultaAsync(m);
        }
        
        public void inserirOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            base.Channel.inserirOcorrencia(o);
        }
        
        public System.Threading.Tasks.Task inserirOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            return base.Channel.inserirOcorrenciaAsync(o);
        }
        
        public void editarOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            base.Channel.editarOcorrencia(o);
        }
        
        public System.Threading.Tasks.Task editarOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            return base.Channel.editarOcorrenciaAsync(o);
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia[] listarOcorrencias() {
            return base.Channel.listarOcorrencias();
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia[]> listarOcorrenciasAsync() {
            return base.Channel.listarOcorrenciasAsync();
        }
        
        public Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia pesquisaOcorrencia(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            return base.Channel.pesquisaOcorrencia(o);
        }
        
        public System.Threading.Tasks.Task<Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia> pesquisaOcorrenciaAsync(Morada_da_paz_Forms.Morada_da_paz_WebService.ocorrencia o) {
            return base.Channel.pesquisaOcorrenciaAsync(o);
        }
    }
}
